name: promoterai
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.12.12
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3.1
  - python=3.9.18
  - readline=8.2
  - setuptools=68.2.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
  - pip:
    - absl-py==2.0.0
    - astunparse==1.6.3
    - cachetools==5.3.2
    - certifi==2023.11.17
    - charset-normalizer==3.3.2
    - flatbuffers==23.5.26
    - gast==0.5.4
    - google-auth==2.25.2
    - google-auth-oauthlib==1.2.0
    - google-pasta==0.2.0
    - grpcio==1.60.0
    - h5py==3.10.0
    - idna==3.6
    - importlib-metadata==7.0.1
    - keras==2.15.0
    - libclang==16.0.6
    - markdown==3.5.1
    - markupsafe==2.1.3
    - ml-dtypes==0.2.0
    - numpy==1.26.2
    - nvidia-cublas-cu12==12.2.5.6
    - nvidia-cuda-cupti-cu12==12.2.142
    - nvidia-cuda-nvcc-cu12==12.2.140
    - nvidia-cuda-nvrtc-cu12==12.2.140
    - nvidia-cuda-runtime-cu12==12.2.140
    - nvidia-cudnn-cu12==8.9.4.25
    - nvidia-cufft-cu12==11.0.8.103
    - nvidia-curand-cu12==10.3.3.141
    - nvidia-cusolver-cu12==11.5.2.141
    - nvidia-cusparse-cu12==12.1.2.141
    - nvidia-nccl-cu12==2.16.5
    - nvidia-nvjitlink-cu12==12.2.140
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==23.2
    - pandas==2.1.4
    - protobuf==4.23.4
    - pyasn1==0.5.1
    - pyasn1-modules==0.3.0
    - pybigwig==0.3.22
    - pyfaidx==0.8.1.1
    - python-dateutil==2.8.2
    - pytz==2023.3.post1
    - requests==2.31.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - six==1.16.0
    - tensorboard==2.15.1
    - tensorboard-data-server==0.7.2
    - tensorflow==2.15.0.post1
    - tensorflow-estimator==2.15.0
    - tensorflow-io-gcs-filesystem==0.35.0
    - termcolor==2.4.0
    - tqdm==4.66.1
    - typing-extensions==4.9.0
    - tzdata==2023.4
    - urllib3==2.1.0
    - werkzeug==3.0.1
    - wrapt==1.14.1
    - zipp==3.17.0
